Add Bingo Brewers
ModMalwareInvestigation/SkyBlockModWiki pull request #21
Opened 2024-02-28 02:51 UTC by IndigoPolecat

2024-04-06 23:33 UTC, Zickles approved these changes

2024-04-07 20:25 UTC, Su386yt approved these changes

2024-08-04 17:37 UTC, ILikePlayingGames submitted a review, later dismissed

2024-08-04 17:39 UTC, jani270 requested changes

2024-08-04 17:39 UTC, jani270 commented on docs/mod-lists/skyblock-mod-list.md
> +    - Download: https://github.com/IndigoPolecat/BingoBrewers
```suggestion
    - Download: https://github.com/IndigoPolecat/BingoBrewers/releases
```

2024-08-04 17:41 UTC, merged